### ISSUE TITLE
Deploy a stage environment with a snapshot of prod data

### ISSUE THREAD

**Issue by thebho** [maryvilledev/codesplain-lambdas#40] opened 2017-04-07 20:03 UTC
Need to be able to test the data structures currently in prod, before deploying the changes

Design to easily switch that env to point to prod after smoke testing

**Comment by thebho** [comment] 2017-04-07 20:12
http://stackoverflow.com/questions/5194552/is-it-possible-to-copy-all-files-from-one-s3-bucket-to-another-with-s3cmd

**Comment by dane-johnson** [comment] 2017-04-10 20:41
@thebho Is this a duplicate of #31?

**Closed** 2017-04-14 17:45 UTC
Labels: AWS/Infra, ready
